### ISSUE TITLE
the .app file doesnot open

### ISSUE THREAD

**Issue by hb2708** [bumptop/BumpTop#2]
I downloaded the dmg from.
https://bumptop.github.io/

but it doesn't work on mac os sierra

**Comment by chrisbensonpdx** [comment]
In order to run BumpTop on Mac OS Sierra, you have to install X11 from https://www.xquartz.org. X11 used to come with OS X by default but now it's an optional download. I've found that BumpTop on Sierra is a little buggy, but it does work and is fun to use!

**Comment by anandx** [comment]
Great to hear it works on Sierre!  Nice find @chrisbensonpdx re: X11 tip.  Thanks!

**Comment by anandx** [comment]
updated the readme so people know about the x11 issue.
